# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/searchwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(823, 587)
        self.txtSearch = QtWidgets.QLineEdit(Form)
        self.txtSearch.setGeometry(QtCore.QRect(20, 20, 789, 23))
        self.txtSearch.setObjectName("txtSearch")
        self.btnSearch = QtWidgets.QPushButton(Form)
        self.btnSearch.setGeometry(QtCore.QRect(20, 50, 789, 23))
        self.btnSearch.setObjectName("btnSearch")
        self.btnCloseSearch = QtWidgets.QPushButton(Form)
        self.btnCloseSearch.setGeometry(QtCore.QRect(20, 80, 789, 23))
        self.btnCloseSearch.setObjectName("btnCloseSearch")
        self.treeStationSearchResult = QtWidgets.QTreeWidget(Form)
        self.treeStationSearchResult.setGeometry(QtCore.QRect(20, 150, 791, 421))
        self.treeStationSearchResult.setObjectName("treeStationSearchResult")
        self.btnAddStation = QtWidgets.QPushButton(Form)
        self.btnAddStation.setGeometry(QtCore.QRect(20, 110, 789, 23))
        self.btnAddStation.setObjectName("btnAddStation")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnSearch.setText(_translate("Form", "Search"))
        self.btnCloseSearch.setText(_translate("Form", "Close"))
        self.treeStationSearchResult.headerItem().setText(0, _translate("Form", "name"))
        self.treeStationSearchResult.headerItem().setText(1, _translate("Form", "url"))
        self.btnAddStation.setText(_translate("Form", "Add Station"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
