# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/searchwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(650, 450))
        Form.setMaximumSize(QtCore.QSize(65535, 65535))
        Form.setMouseTracking(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtSearch = QtWidgets.QLineEdit(self.widget)
        self.txtSearch.setObjectName("txtSearch")
        self.horizontalLayout_2.addWidget(self.txtSearch)
        self.comboSearchOption = QtWidgets.QComboBox(self.widget)
        self.comboSearchOption.setObjectName("comboSearchOption")
        self.comboSearchOption.addItem("")
        self.comboSearchOption.addItem("")
        self.comboSearchOption.addItem("")
        self.horizontalLayout_2.addWidget(self.comboSearchOption)
        self.btnSearch = QtWidgets.QPushButton(self.widget)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout_2.addWidget(self.btnSearch)
        self.verticalLayout.addWidget(self.widget)
        self.treeStationSearchResult = QtWidgets.QTreeWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.treeStationSearchResult.sizePolicy().hasHeightForWidth())
        self.treeStationSearchResult.setSizePolicy(sizePolicy)
        self.treeStationSearchResult.setFrameShadow(QtWidgets.QFrame.Plain)
        self.treeStationSearchResult.setObjectName("treeStationSearchResult")
        self.verticalLayout.addWidget(self.treeStationSearchResult)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnAddStation = QtWidgets.QPushButton(self.widget_2)
        self.btnAddStation.setObjectName("btnAddStation")
        self.horizontalLayout_3.addWidget(self.btnAddStation)
        self.btnClearSearch = QtWidgets.QPushButton(self.widget_2)
        self.btnClearSearch.setObjectName("btnClearSearch")
        self.horizontalLayout_3.addWidget(self.btnClearSearch)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnCloseSearch = QtWidgets.QPushButton(self.widget_2)
        self.btnCloseSearch.setObjectName("btnCloseSearch")
        self.horizontalLayout_3.addWidget(self.btnCloseSearch)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.txtSearch.setPlaceholderText(_translate("Form", "Search by Name"))
        self.comboSearchOption.setItemText(0, _translate("Form", "Name"))
        self.comboSearchOption.setItemText(1, _translate("Form", "Tag"))
        self.comboSearchOption.setItemText(2, _translate("Form", "Country"))
        self.btnSearch.setText(_translate("Form", "Search"))
        self.treeStationSearchResult.setSortingEnabled(True)
        self.treeStationSearchResult.headerItem().setText(0, _translate("Form", "Name"))
        self.treeStationSearchResult.headerItem().setText(1, _translate("Form", "URL"))
        self.treeStationSearchResult.headerItem().setText(2, _translate("Form", "Tags"))
        self.treeStationSearchResult.headerItem().setText(3, _translate("Form", "Country"))
        self.treeStationSearchResult.headerItem().setText(4, _translate("Form", "Codec"))
        self.treeStationSearchResult.headerItem().setText(5, _translate("Form", "Bitrate"))
        self.btnAddStation.setText(_translate("Form", "Add Station"))
        self.btnClearSearch.setText(_translate("Form", "Clear"))
        self.btnCloseSearch.setText(_translate("Form", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
